### ISSUE TITLE
Requests error when packaging evelink based app w/py2exe

### ISSUE THREAD

**Issue by Prodigalhacker** [eve-val/evelink#206]
I'm not sure if this is the correct place for this (my apologies if not, I'm still pretty new at this), but it was the closest thing that seemed to make sense.

I've written an app for my corp that uses evelink to do all its work with EVE API. It works great when I run just the python script itself, but if I package it into an exe with py2exe, I get the following error when trying to run the compiled executable:

Traceback (most recent call last):
  File "CounterIntel.py", line 9, in <module>
  File "flagged_list.pyc", line 39, in <module>
  File "evelink\api.pyc", line 510, in wrapper
  File "evelink\api.pyc", line 265, in get
  File "evelink\api.pyc", line 315, in send_request
  File "evelink\api.pyc", line 372, in requests_request
requests.exceptions.SSLError: [Errno 2] No such file or directory

I've done some searching on google, and it seems like there's an issue with requests looking for the SSL cert in a weird place and/or py2exe not including the cert in the library when it builds the exe. I've tried updating the setup.py to include the cert but that produces the same error.

**Comment by ayust** [comment]
This doesn't appear to be EVELink-specific - see for example http://stackoverflow.com/questions/17158529/fixing-ssl-certificate-error-in-exe-compiled-with-py2exe-or-pyinstaller

Thus I'm not sure I really have much in the way of advice for you beyond what's there or in the rest of Google - you probably would be better asking the py2exe or the requests folks, if you're not able to find an answer by searching.
