### ISSUE TITLE
timeout for api requests

### ISSUE THREAD

**Issue by bastianh** [eve-val/evelink#207]
Lately I sometimes have problem that the api server don't answer request, but also won't close the connection. I have a watchdog that kills my script after 10 minutes, but I think it would be much more reasonable to have a shorter timeout when doing the the request.

http://docs.python-requests.org/en/latest/user/quickstart/#timeouts

I could create a patch, what timout would you think would be ok ? I guess it should be one minute max?

The function hangs in:

python3.4/ssl.py in read
                v = self._sslobj.read(len, buffer)

**Comment by ayust** [comment]
One minute would probably be plenty.
